### ISSUE TITLE
Installer script fails

### ISSUE THREAD

**Issue by Wordsmith9091** [LeGeRyChEeSe/Sunshine-AIO#28]
The first time I tried running the powershell script, it saw that python wasn't installed and auto-installed it.

But after that, some text whizzes by and the powershell window closes. The script is failing somewhere but it's going by too quickly to see what the problem is.

**Comment by LeGeRyChEeSe** [comment]
Hello, I spent my entire day on this problem to finally resolve it. There should be no more problems, let me know if you still have any problems.

**Comment by LeGeRyChEeSe** [comment]
It's true that I forgot to check if git was installed, I need to add it. However, for the rest, simply delete the folder that you created manually and relaunch the script.
Try putting the path to your desktop like C:\Users\<your_username>\Desktop and see if the folder is created and the program launches.

**Comment by Wordsmith9091** [comment]
That works to get it installed!

Unfortunately, now that it is, I'm running into another problem that I also had when I last tried AIO, before you had the powershell script available. When I try to launch an app in Moonlight, it hands on the "establishing connection" screen, seemingly indefinitely. On my PC, I see the monitor(s) flash the display on and off a couple of times, as they would during a change to my display setup, like plugging in a new monitor (possible when it's seeing the virtual display connected). But then nothing happens after that, and the machine becomes laggy to the point that it's nearly unresponsive, and I have to reset it before it works normally again.

**Comment by LeGeRyChEeSe** [comment]
Can you share your sunshine-virtual-monitor logs ? located in Sunshine-AIO\tools\sunshine-virtual-monitor-main\sunvdm.log

Also take a look in this issue there is a workaround you can try : https://github.com/Cynary/sunshine-virtual-monitor/issues/16#issuecomment-2506932817

**Comment by Delamain813** [comment]
I just wanted to report that I ran into these exact same issues. Using the direct path to my desktop solved that issue, but I had the same problem with the handshake not working. However, I also run two displays, my desktop and my tv. I unplugged the desktop display and tried connecting again and it worked. I had a feeling the handshake was failing because there seems to be some kind of problem with two displays being connected to my pc. This was never an issue before the script powershell installation, but I do suspect it had something to do with a windows update, after which even my old sunshine/moonlight setup did not work anymore.

**Comment by mppilat** [comment]
Same issue here. After installig git and running script i get 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt
Then install fails and closes powershell window. Using Sunshine-AIO.ps1, hovewer, allows to retain windows contents:

![Image](https://github.com/user-attachments/assets/85bf3c2e-e4f6-4d60-a03f-9fa7241c7065)

Tried previous solutions of deleting folders, changing location, reinstalling git (maybe i use some wront install settings there?). Nothing works, should i maybe add .git file somewhere?

**Comment by LeGeRyChEeSe** [comment]
Hello @mppilat, make sure to correctly delete the Sunshine-AIO folder and reexecute the `irm https://sunshine-aio.com/script.ps1 | iex` command from a powershell window. Make sure the path contains no spaces. For your example if you want to install it in the D:\ folder, then just type D:\

I've just tried now and it worked, so maybe try to reinstall once, and if you still got the issue, please send some logs and the folder's content.

**Comment by mppilat** [comment]
Somehow it worked this time.
I created one test repo before running script, maybe that triggered git to start working properly. 
Installed everything, will test soon how streaming works. Thanks for help and this fantastic automation. I hope everything will work :)

**Comment by NJMRgit** [comment]
I'm at a complete loss as to why I can't seem to get the script to run. 

This is what powershell says just before it closes 

Running the program ...
Traceback (most recent call last):
File "C:\Users\Username\Desktop\Sunshine\Sunshine-AIO\src\main.py", line 2, in <module>
from misc.MenuHandler import MenuHandler
File "C:\Users\Username\Desktop\Sunshine\Sunshine-AIO\src\misc\MenuHandler.py", line 4, in <module>
from misc.Config import DownloadManager
File "C:\Users\Username\Desktop\Sunshine\Sunshine-AIO\src\misc\Config.py", line 4, in <module>
import requests
ModuleNotFoundError: No module named 'requests'

**Comment by kerashistorm** [comment]
That's a python error.  It looks like the third party requests library didn't get installed.  That will be an easy fix, fortunately.  One way is to uninstall Python and everything related before running the install script again.  Alternatively, if you are using python for something else, just install the requests library with pip.

**Comment by LeGeRyChEeSe** [comment]
> I'm at a complete loss as to why I can't seem to get the script to run.
> 
> This is what powershell says just before it closes
> 
> Running the program ... Traceback (most recent call last): File "C:\Users\Username\Desktop\Sunshine\Sunshine-AIO\src\main.py", line 2, in from misc.MenuHandler import MenuHandler File "C:\Users\Username\Desktop\Sunshine\Sunshine-AIO\src\misc\MenuHandler.py", line 4, in from misc.Config import DownloadManager File "C:\Users\Username\Desktop\Sunshine\Sunshine-AIO\src\misc\Config.py", line 4, in import requests ModuleNotFoundError: No module named 'requests'

Hello, did you install the program with the `irm https://sunshine-aio.com/script.ps1 | iex` command from a powershell ? It should give you no error if you set a correct path when requested like `C:\Users\Username\Desktop`

**Comment by NJMRgit** [comment]
So I originally installed it some months ago and it worked fine
I'd changed some settings in sunshine related to the virtual display and wanted to repair my installation so I ran the installer again in powershell. 

The first time it ran it told my python wasn't installed (which is odd because it was never removed from the time I'd originally installed) and installed it, and then I was able to set the directory location. After it's created the directory powershell outputs what I posted and then closes. I've tried pointing the directory to the root of 3 seperate drives as well as the desktop and they all return the same error

**Comment by LeGeRyChEeSe** [comment]
Go to the Sunshine-AIO folder and open a Terminal from this folder then type this command to show every installed packages in the python virtual environment : `.\.venv\Scripts\pip.exe freeze`

You should see this output:
```py
certifi==2024.8.30
charset-normalizer==3.3.2
idna==3.8
ordered-set==4.1.0
python-dotenv==1.0.1
requests==2.32.3
urllib3==2.2.2
zstandard==0.23.0
```

Otherwise you should try to install every missing package with `.\.venv\Scripts\pip.exe install <package_name>`

I see in your logs that the `requests` package is missing (this is weird and should automatically be installed) so try to manually install it with `.\.venv\Scripts\pip.exe install requests`

**Comment by LeGeRyChEeSe** [comment]
This command will install every missing packages if you're lazy: `.\.venv\Scripts\pip.exe install -r requirements.txt`

**Comment by LeGeRyChEeSe** [comment]
The latest commit should resolve the issue.

**Comment by NJMRgit** [comment]
It's still giving me ImportError: Module use of python312.dll conflicts with this version of Python.

**Comment by LeGeRyChEeSe** [comment]
make sure you don't have any other version of Python installed, because the error says you have another version of Python that causes conflicts

**Comment by BrickPotato** [comment]
Log attached:

[sunshine_aio_app_20250913_095804.log](https://github.com/user-attachments/files/22311690/sunshine_aio_app_20250913_095804.log)
[sunshine_aio_20250913_095740.log](https://github.com/user-attachments/files/22311691/sunshine_aio_20250913_095740.log)

**Comment by LeGeRyChEeSe** [comment]
Hello @BrickPotato can you confirm the issue is solved with the latest update ?
