### ISSUE TITLE
CMD GUI closes immediately

### ISSUE THREAD

**Issue by InZillaWeTrust** [LeGeRyChEeSe/Sunshine-AIO#6]
Following the steps within the recently added AIO script does not complete the install.

I successfully can run the script with the exception of the line `pip install -r requirements.txt` requires me to hit Enter for it to run. 

However when I attempt to run the `src\main.py` command a terminal window opens and closes immediately and nothing else happens. I have also tried the `py src\main.py` command which does not work. I have tried this a couple of times using Powershell, CMD both elevated and not elevated.

```
PowerShell 7.4.5
PS C:\Software> git clone --branch dev-AIO https://github.com/LeGeRyChEeSe/Sunshine-AIO.git
Cloning into 'Sunshine-AIO'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 26 (delta 3), reused 22 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (26/26), 427.33 KiB | 1.75 MiB/s, done.
Resolving deltas: 100% (3/3), done.
PS C:\Software> cd Sunshine-AIO
PS C:\Software\Sunshine-AIO> py -m venv virtualenv-python-sunshine-aio
PS C:\Software\Sunshine-AIO> virtualenv-python-sunshine-aio\Scripts\activate.bat
PS C:\Software\Sunshine-AIO> pip install -r requirements.txt
Requirement already satisfied: certifi==2024.7.4 in c:\users\jakec\.pyenv\pyenv-win\versions\3.12.5\lib\site-packages (from -r requirements.txt (line 1)) (2024.7.4)
Requirement already satisfied: charset-normalizer==3.3.2 in c:\users\jakec\.pyenv\pyenv-win\versions\3.12.5\lib\site-packages (from -r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna==3.7 in c:\users\jakec\.pyenv\pyenv-win\versions\3.12.5\lib\site-packages (from -r requirements.txt (line 3)) (3.7)
Requirement already satisfied: requests==2.32.3 in c:\users\jakec\.pyenv\pyenv-win\versions\3.12.5\lib\site-packages (from -r requirements.txt (line 4)) (2.32.3)
Requirement already satisfied: urllib3==2.2.2 in c:\users\jakec\.pyenv\pyenv-win\versions\3.12.5\lib\site-packages (from -r requirements.txt (line 5)) (2.2.2)
PS C:\Software\Sunshine-AIO> src\main.py
PS C:\Software\Sunshine-AIO> py src\main.py
Traceback (most recent call last):
  File "C:\Software\Sunshine-AIO\src\main.py", line 1, in <module>
    from functions import *
  File "C:\Software\Sunshine-AIO\src\functions.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PS C:\Software\Sunshine-AIO> git pull
Already up to date.
PS C:\Software\Sunshine-AIO>
```

**Comment by LeGeRyChEeSe** [comment]
Hi,
Please download the latest update of the script.
Go into the `Sunshine-AIO` folder and run these command to get the latest release:
```git
git pull
```
Then from the same folder run this command to execute the script:
```batch
virtualenv-python-sunshine-aio\Scripts\python.exe src\main.py
```

Your issue should be solved.
